name: deploy to ec2 with jar

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: build jar
        working-directory: .
        #        명령어가 두줄 이상이면 |를 넣어준다
        run: |
          chmod 777 ./gradlew
          ./gradlew bootJar

      - name: copy jar to ec2
        uses: appleboy/scp-action@master
        with:
          #          ec2에서 생성한 instance1의 public dns
          host: ec2-54-180-239-241.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          #          pemkey를 통해 해당 인스턴스에 접근 -> 근대 배포할 거니까 직접 넣으면 안됨.
          key: ${{secrets.EC2_PEMKEY}}
          #          source : 어디에서 어디로 배포할 것인지
          source: "./build/libs/*.jar"
          #            어디로 베포할 것인지 - 만드는 가상 컴퓨터의 home 밑에 ubuntu
          target: "/home/ubuntu"